require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('awesome_tables', '0.0.4') do |p|
  p.description    = "A gem for some awesome tables"
  p.url            = "http://github.com/danengle/awesome_tables"
  p.author         = "Dan Engle"
  p.email          = "engle.68 @nospam@ gmail.com"
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = []
end
